import { JSX } from "react";
import {
  FaReact,
  FaJava,
  FaHtml5,
  FaCss3Alt,
  FaPython,
  FaUnity,
  FaGit,
  FaDocker,
} from "react-icons/fa";
import {
  SiTypescript,
  SiTailwindcss,
  SiElectron,
  SiVite,
  SiFirebase,
  SiUnrealengine,
  SiOpengl,
  SiNodedotjs,
  SiExpress,
  SiJavascript,
  SiMysql,
  SiMongodb,
  SiExpo,
  SiNextdotjs,
  SiSqlite,
  SiGithubactions,
  SiBlender,
} from "react-icons/si";

// Mapping tech to icons
export const techIcons: Record<string, JSX.Element> = {
  typescript: <SiTypescript className="text-sky-500" />,
  javascript: <SiJavascript className="text-yellow-400" />,
  tailwindcss: <SiTailwindcss className="text-cyan-400" />,
  electron: <SiElectron className="text-blue-400" />,
  react: <FaReact className="text-blue-500" />,
  "react-native": <FaReact className="text-blue-500" />,
  vite: <SiVite className="text-purple-500" />,
  firebase: <SiFirebase className="text-yellow-500" />,
  "unreal-engine": (
    <SiUnrealengine className="text-gray-700 dark:text-gray-200" />
  ),
  "c++": <span className="text-blue-600 font-bold">C++</span>,
  "c#": <span className="text-purple-500 font-bold">C#</span>,
  java: <FaJava className="text-red-500" />,
  python: <FaPython className="text-blue-400" />,
  opengl: <SiOpengl className="text-green-500" />,
  mcp: <span className="text-pink-500 font-bold">MCP</span>,
  html: <FaHtml5 className="text-orange-500" />,
  css: <FaCss3Alt className="text-blue-500" />,
  nodejs: <SiNodedotjs className="text-green-600" />,
  express: <SiExpress className="text-gray-800 dark:text-white" />,
  mysql: <SiMysql className="text-orange-500" />,
  mongodb: <SiMongodb className="text-green-600" />,
  sqlite: <SiSqlite className="text-blue-400" />,
  nextjs: <SiNextdotjs className="text-black dark:text-white" />,
  expo: <SiExpo className="text-purple-500" />,
  docker: <FaDocker className="text-blue-500" />,
  git: <FaGit className="text-orange-500" />,
  "github-actions": <SiGithubactions className="text-purple-400" />,
  blender: <SiBlender className="text-orange-500" />,
  unity: <FaUnity className="text-gray-900 dark:text-white" />,
};

// Mapping tech to docs link
export const techLinks: Record<string, string> = {
  typescript: "https://www.typescriptlang.org/docs/",
  javascript: "https://www.w3schools.com/js/",
  tailwindcss: "https://tailwindcss.com/docs",
  electron: "https://www.electronjs.org/docs",
  react: "https://react.dev/",
  "react-native": "https://reactnative.dev/docs/getting-started",
  vite: "https://vitejs.dev/guide/",
  firebase: "https://firebase.google.com/docs",
  "unreal-engine": "https://docs.unrealengine.com/",
  "c++": "https://cplusplus.com/doc/tutorial/",
  "c#": "https://learn.microsoft.com/en-us/dotnet/csharp/",
  java: "https://docs.oracle.com/javase/tutorial/",
  python: "https://docs.python.org/3/",
  opengl: "https://www.khronos.org/opengl/wiki",
  mcp: "https://minecraft.fandom.com/wiki/Tutorials/Programs_and_editors/Mod_Coder_Pack",
  html: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  css: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  nodejs: "https://nodejs.org/docs",
  express: "https://expressjs.com/en/starter/installing.html",
  mysql: "https://dev.mysql.com/doc/",
  mongodb: "https://www.mongodb.com/docs/",
  sqlite: "https://www.sqlite.org/docs.html",
  nextjs: "https://nextjs.org/docs",
  expo: "https://docs.expo.dev/",
  docker: "https://docs.docker.com/",
  git: "https://git-scm.com/doc",
  "github-actions": "https://docs.github.com/en/actions",
  blender: "https://docs.blender.org/manual/en/latest/",
  unity: "https://docs.unity3d.com/Manual/index.html",
};
